apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-app-figo
spec:
  selector:
    matchLabels:
      app: argocd-app-figo
  template:
    metadata:
      labels:
        app: argocd-app-figo
    spec:
      containers:
      - name: argocd-app-giho
        #image: utibeabasi6/argocd-code:v1.0.8
		image: nginxdemos/hello
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: argocd-svc-figo
spec:
  selector:
    app: argocd-app-figo
  ports:
  - port: 80
    targetPort: 5000
